variables:
  DATABASE_URL: postgresql://prisma:prisma@postgres:5432/tests
  POSTGRES_USER: prisma
  POSTGRES_PASSWORD: prisma
  POSTGRES_DB: tests
  SECRET_KEY: 3c61a32bd38e0727dab133c19c266bb412b4ddf12a80f2efba805b6f7aff59f13a4e513a0d3a76ac2164280f93566871f9091feda4aedf2b7daf770eb3597207

stages:
  - build
  - setup
  - unit
  - integration
  - e2e

test:unit:
  stage: unit
  image: node:latest
  services:
    - name: postgres:13
      alias: postgres
  tags:
    - docker
  script:
    - yarn install --no-progress
    - yarn prisma migrate deploy
    - yarn test:unit

test:int:
  stage: integration
  image: node:latest
  services:
    - name: postgres:13
      alias: postgres
  tags:
    - docker
  script:
    - yarn install --no-progress
    - yarn prisma migrate deploy
    - yarn test:int
  dependencies:
    - test:unit

test:e2e:
  stage: e2e
  image: node:latest
  services:
    - name: postgres:13
      alias: postgres
  tags:
    - docker
  script:
    - yarn install --no-progress
    - yarn prisma migrate deploy
    - yarn test:e2e
  dependencies:
    - test:int
