# Set the version of docker compose to use
version: "3.9"

# The containers that compose the project
services:
  webapp:
    restart: unless-stopped
    depends_on:
      - postgres
    build:
      dockerfile: ./Dockerfile
    networks:
      - postgres_network
      - nginx_network
    deploy:
      mode: replicated
      replicas: 3
    environment:
      - DATABASE_URL=${DATABASE_URL_DOCKER}
      - SECRET_KEY=${SECRET_KEY}

  webapp_mirror:
    restart: unless-stopped
    depends_on:
      - postgres_repl
    build:
      dockerfile: ./Dockerfile
    networks:
      - postgres_network
      - nginx_network
    environment:
      - DATABASE_URL=${MIRRORDB_URL}
      - SECRET_KEY=${SECRET_KEY}

  postgres:
    image: "bitnami/postgresql:latest"
    container_name: postgres
    environment:
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=replicator
      - POSTGRESQL_REPLICATION_PASSWORD=password
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=${DB_PASSWORD}
      - POSTGRESQL_DATABASE=web
    ports:
      - "5435:5432"
    networks:
      - postgres_network
    volumes:
      - ./postgres:/bitnami/postgresql

  postgres_repl:
    image: "bitnami/postgresql:latest"
    container_name: postgres_repl
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_MASTER_HOST=postgres
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
      - POSTGRESQL_REPLICATION_USER=replicator
      - POSTGRESQL_REPLICATION_PASSWORD=password
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=${DB_PASSWORD}
      - POSTGRESQL_DATABASE=web
    depends_on:
      - postgres
    ports:
      - "5436:5432"
    networks:
      - postgres_network
    volumes:
      - ./postgres_repl:/bitnami/postgresql

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - postgres_network
      - nginx_network

  nginx:
    image: "byjg/nginx-extras"
    container_name: nginx
    volumes:
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./etc/static:/static
      - ./README.md:/static/doc/README.md
    depends_on:
      - webapp
    ports:
      - "80:8080"
    networks:
      - nginx_network
    restart: unless-stopped

volumes:
  postgres:
  pgadmin-data:
  postgres_repl:

networks:
  postgres_network:
    driver: bridge
  nginx_network:
    driver: bridge
