FROM node:latest

WORKDIR /usr/src/app

COPY package.json yarn.lock tsconfig.json openapi.json ./
COPY src ./src
COPY benchmarks ./benchmarks
RUN mkdir ./prisma
COPY ./prisma/pg.prisma ./prisma/schema.prisma
COPY .env.pg .env

RUN yarn install --immutable --immutable-cache --check-cache

EXPOSE 3000

CMD [ "yarn", "bench:pg" ]
